<script src="<?php echo _WEB_ROOT ?>/public/assets/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/splide.min.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/smooth-scrollbar.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/slimselect.min.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/plyr.min.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/photoswipe.min.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/photoswipe-ui-default.min.js"></script>
<script src="<?php echo _WEB_ROOT ?>/public/assets/js/main.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.21.9/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.21.9/dist/js/uikit-icons.min.js"></script>